spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cooklion}
    username: ${POSTGRES_USER:cooklion}
    password: ${POSTGRES_PASSWORD:cooklion}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
