version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cooklion-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cooklion}
      POSTGRES_USER: ${POSTGRES_USER:-cooklion}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cooklion}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
