spring:
  datasource:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/cooklion}
      username: ${POSTGRES_USER:cooklion}
      password: ${POSTGRES_PASSWORD:cooklion}
  jpa:
      open-in-view: false
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          jdbc:
            time_zone: UTC
  logging:
    level:
      org.hibernate.SQL: warn
      org.hibernate.orm.jdbc.bind: warn
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: gemma3:1b #llama3.2:1b #gemma3:1b
          format:  # json or blank
          num-predict: -1 # default: -1, output token cap; TODO: streaming and low value does not work well together
          top-k: 10 # default: 40 higher => more nonsense
          temperature: 0.7 # default 0.8, higher => more creative